export const alllanguages = [
  'Afrikaans',
  'Arabic',
  'Bangla',
  'Bosnian (Latin)',
  'Bulgarian',
  'Cantonese (Traditional)',
  'Catalan',
  'Chinese Simplified',
  'Chinese Traditional',
  'Croatian',
  'Czech',
  'Danish',
  'Dutch',
  'English',
  'Estonian',
  'Fijian',
  'Filipino',
  'Finnish',
  'French',
  'German',
  'Greek',
  'Gujarati',
  'Haitian Creole',
  'Hebrew',
  'Hindi',
  'Hmong Daw',
  'Hungarian',
  'Icelandic',
  'Indonesian',
  'Irish',
  'Italian',
  'Japanese',
  'Kannada',
  'Kazakh',
  'Klingon',
  'Klingon (plqaD)',
  'Korean',
  'Kurdish (Central)',
  'Kurdish (Northern)',
  'Latvian',
  'Lithuanian',
  'Malagasy',
  'Malay',
  'Malayalam',
  'Maltese',
  'Maori',
  'Marathi',
  'Norwegian',
  'Odia',
  'Pashto',
  'Persian',
  'Polish',
  'Portuguese',
  'Punjabi',
  'Querétaro Otomi',
  'Romanian',
  'Russian',
  'Samoan',
  'Serbian (Cyrillic)',
  'Serbian (Latin)',
  'Slovak',
  'Slovenian',
  'Spanish',
  'Swahili',
  'Swedish',
  'Tahitian',
  'Tamil',
  'Telugu',
  'Thai',
  'Tongan',
  'Turkish',
  'Ukrainian',
  'Urdu',
  'Vietnamese',
  'Welsh',
  'Yucatec Maya',
]
